### ISSUE TITLE
[QUESTION] Updating the API

### ISSUE THREAD

**Issue by vizerei** [dodexahedron/SE-Community-Mod-API#6]
I'm trying to learn a bit about how this API works so perhaps I can contribute in the future.  So forgive me if some of my questions seem a bit dumb.

During each update, it seems that aside from including the KSH updated DLL files, there are some hashes that reference methods that need to be changed.  How on earth do you find out what the new hashes are?

**Comment by dodexahedron** [comment]
De-obfuscation is half voodoo.
I'm not particularly skilled in it, myself, as I've rarely had to do it.
I'm actually trying to learn that part, now, so that I can handle this a little more timely and not have to depend on upstream pushes to fix this.

**Comment by dodexahedron** [comment]
So, after doing it myself, this time around, I can share the experience with you...
First, you need to be using something like ilspy or reflector to look at the assemblies.

Then, look for the obvious ones, first.  For example, the kick/ban methods are pretty easy to find.  The reason for that is there is string data that you can search for (the message that the player was kicked/banned).  Once you find that, you've found the method that you're interested in, and can take its name.

Then there are others that need a little bit of heuristic reasoning coupled with some trial and error.
For example, the PowerProducer class.  First off, that's not really a class in the Sandbox.Game.dll.  It's actually an interface, but whatever.  That's not terribly important, here.  There are two getters we want, as well as one setter.  The two getters will be methods that take no arguments (that's how getters work), and return floats (these are power values, which are floats in the game).  There are three methods with that signature in that interface, so try them out, one by one, until you find the one that gives the correct information for each property.  For example, load up a lone survivor world and check the reactor in-game for its power output values and compare to what you see in SESE for that reactor.  If the values don't match, you guessed the wrong methods. Switch them up and try again until the values match.

That kind of reasoning seems to work pretty well for the majority of stuff I've come across, so far, for the game.

**Comment by vizerei** [comment]
Okay, all of that doesn't sound terribly hard.  My next question is this:  how do we automate that process?

Also, do you happen to know what they use to obfuscate their code?  From what I've found if they use a readily available commercial tool it could be reasonably easy to deobfuscate it...tho I'm betting that's already been tried.

Also, would you mind me having some way to contact you off of opening github issues? :)

**Comment by dodexahedron** [comment]
Pretty sure my email is public in the github repository.  I won't post it here, for reasons of avoiding the web crawlers, but feel free to look in the commit history with a git client to find it.

As far as automating...
That's not really possible, in a meaningful way, else else obfuscation would be pointless to begin with.  The object isn't to de-obfuscate the game - the object is to find the methods we want to call, so that SESE can call them when it needs to.  If we were de-obfuscating the game to build SESE, every user of SESE would need a copy of the de-obfuscated binaries, because the method names would all be different, and that would be straight-up copyright infringement (wrappers are already a legal gray area).

KSH does use a commonly-available commercial tool, but all they're doing is hashing symbol names.  They're not applying nastier obfuscation, such as actual string encryption, structural obfuscation, etc., and they're not changing every symbol name every build.  If they ever do, this job is going to get a LOT harder.

**Comment by vizerei** [comment]
So I believe I connected dots in my head that I didn't succinctly convey when it comes to the deobfuscation and automation.  The basics would be as follows:
1 - Deobfuscate to a copy
2 - Read and Search the deobfuscated copy line by line, while counting, for the methods you are interested in, remember the lines
3 - Read the obfuscated file at the line(s) stored from the previous operation
4 - Parse the obfuscated lines to extract the hashes
5 - Overwrite those hashes in SESE

I know that's high level, but everything I listed here except for the actual deobfuscation I could get done in a bash or powershell script.  Bam, automated.  The only issue I can see is doing the deobfuscation on the command line.

**Comment by dodexahedron** [comment]
De-obfuscation is not really all that meaningful, here, though.  These method names are hashed, not encrypted, and thus that can't be reversed in any reliable fashion (they're clearly salted differently each time, or else they'd be the same hash with every compilation).

And it can't be automated, because you still have to test for each value you changed, to be sure you got the right one in the first place.  The only heuristic I can think of to use is the general method signature for something, and that could change from release to release (except for simple getters and setters).
Since all function calls inside a function body are also hashed, you can't exactly eyeball a function and know its purpose unless there's a string in it that you can use (which is how the kick/ban methods are located).

However, if you want to take a shot at it, the tool you'll want to get familiar with, for the command line decompilation, is probably de4dot.  It is free/open source and can decompile and de-obfuscate quite a range of things.

But, again, de-obfuscated source, in SE, doesn't help you at all, since you still end up with nonsensical symbol names, like "ns1.class1.func1()"
So you should just skip the de-obfuscation step and go straight from decompiled source to find the hashes, in your method above.

**Comment by vizerei** [comment]
Alright, I can look in to using de4dot.  I will need a baseline at some point to compare against.  If Tyrsis doesn't update with Thursday's patch like he hasn't with last Fridays would you be willing to find those hashes for me to use to compare against both the obfuscated and deobfuscated code?

**Comment by dodexahedron** [comment]
I updated this week's already. You can compare those if you like.

**Comment by vizerei** [comment]
I don't see the hashes updated in the commits, am I missing something?

**Comment by dodexahedron** [comment]
Definitely.
91254fb392e67217b01cc9ca4e9cc6c967af9311
affffaf8a9d4ac3a672bc036aedc3efe05041ae5
69ba402dc0092cfdb68005473801a2ec566e9e01
